steps:
- name: 'bash'
  id: Verzeichnis auflisten1
  args: ['ls', '-la']
- name: 'bash'
  id: Verzeichnis erstellen
  args: ['mkdir', 'market_data']  
- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'gs://fx-research-poc-1/market_data/population_by_country_2020.csv', './market_data/population_by_country_2020.csv']
- name: 'bash'
  id: Verzeichnis auflisten2
  args: ['ls', '-la', 'market_data']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/fxresearch-poc/rexample', '.' ]
- name: 'gcr.io/cloud-builders/gsutil' 
  id: Kopieren der App in den Cloud Bucket
  args: ['cp', '-rP', '*', 'gs://fx-research-poc-1/']
#- name: 'gcr.io/cloud-builders/gcloud' 
#  entrypoint: 'bash' args: ['gcloud' 'compute' , 'scp' , '*', 'username@instance-name:/home/directory' , '--zone=europe-west3-c', '--recurse']

