steps:
- name: 'bash'
  id: Verzeichnis auflisten
  args: ['ls', '-la']
- name: 'gcr.io/cloud-builders/gsutil' 
  id: Kopieren der App in den Cloud Bucket
  args: ['cp', '-rP', '*', 'gs://fxresearch-poc-shiny-apps/']
- name: 'rocker/r-base'
  id: R-Skript ausfuehren
  args: ['Rscript', './process_market_data.R']
#- name: 'gcr.io/cloud-builders/gcloud' 
#  entrypoint: 'bash' args: ['gcloud' 'compute' , 'scp' , '*', 'username@instance-name:/home/directory' , '--zone=europe-west3-c', '--recurse']

