steps:
- name: 'bash'
  args: ['ls', '-la']
- name: 'gcr.io/cloud-builders/gsutil' 
  args: ['cp', '-rP', '*', 'gs://fxresearch-poc-shiny-apps/']
- name: 'rocker/r-base'
  id: Hello R
  args: ["R", "-e", "paste0('1 + 1 = ', 1+1)"]
#- name: 'gcr.io/cloud-builders/gcloud' 
#  entrypoint: 'bash' args: ['gcloud' 'compute' , 'scp' , '*', 'username@instance-name:/home/directory' , '--zone=europe-west3-c', '--recurse']

