steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'eu.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:$SHORT_SHA', '.' ]
#- name: 'gcr.io/cloud-builders/docker'
#  args: [ 'push', 'eu.gcr.io/${PROJECT_ID}/${_SERVICE_NAME}:$SHORT_SHA']

